### PR TITLE
Indonesian translation

### PR DESCRIPTION
**Pull request by chairulakmal**
Hi @nanexcool 

This is an initial commit for Indonesian translation. Some of the terms are not familiar to Indonesian programmers yet, so I will change it if the community start adopting some of the terms.

Previously I have translated parts of ethereum.org website into Indonesian.

Cheers

### CODE REVIEW

**Comment by nanexcool** [comment]
Great, thank you!! Merging right now.

One question (and I still need to add this) to the strings: for the language selector should I use "Indonesia", "Bahasa Indonesia" or something else?  Thank you!

**Comment by chairulakmal** [comment]
I think "Bahasa Indonesia" is the most appropriate one to use for the language @nanexcool 
Thanks for the merge

**Comment by nanexcool** [comment]
Thank you @chairulakmal ! 

One last thing, I'm putting together a `CONTRIBUTORS` file, let me know how to add you. Link to your Github or a Twitter account?

**Comment by chairulakmal** [comment]
You can link my github account [@chairulakmal](https://github.com/chairulakmal)
Thanks!

**Pull request merged**
