### PR TITLE
Added Russian

### PR DESCRIPTION
**Pull request by Davidutro**
<3

### CODE REVIEW

**Comment by nanexcool** [comment]
Can't really say anything about your Russian, but I can say that these `%{знак}` are substitutions and should not be changed! ;)

So they should stay as `%{token}` or whatever, and the code will add `Dai` or `ETH` or any of the others :D

**Comment by Davidutro** [comment]
I'll fix it in a bit and update this PR

**Comment by Davidutro** [comment]
Fixed! lmk if there is anything else that needs to be changed @nanexcool

**Comment by nanexcool** [comment]
Looks great man!

**Pull request merged**
